# Coderabbit Configuration for CSD325: Advanced Python

# [cite_start]Set the language for all reviews. [cite: 1]
system_language: "en-US"

# A little fun is good, but let's keep the PR comments focused on the review.
[cite_start]disable_poem: true # [cite: 1]

# [cite_start]It's good practice to ignore draft PRs until they are ready for review. [cite: 1]
ignore_draft_pr: true

# Ignore PRs with "WIP" (Work In Progress) in the title.
[cite_start]ignored_titles: "WIP" # [cite: 1]

# --------------------------------------------------------------------------
# --- Path Filtering: Focus the review on what matters most in this course ---
# --------------------------------------------------------------------------
[cite_start]path_filters: # [cite: 1]
  # Explicitly include all Python files for review.
  - "**/*.py"
  # Exclude common files and folders that don't need a code review.
  - "!**/__pycache__/**" # Ignore Python's cache directories.
  - "!**/venv/**"        # Ignore virtual environment folders.
  - "!**/.venv/**"
  - "!**/*.pyc"         # Ignore compiled Python files.
  - "!**/*.sqlite3"     # Ignore the Django database file.
  # Exclude assignment documents and assets.
  - "!**/*.pdf"
  - "!**/*.docx"
  - "!**/*.md"
  - "!**/*.zip"
  - "!**/*.png"
  - "!**/*.jpg"
  - "!**/*.mp4"

# --------------------------------------------------------------------------
# --- Custom Instructions: Your AI Mentor's Cheat Sheet 🐍 ---
# --------------------------------------------------------------------------
[cite_start]file_path_instructions: # [cite: 1]
  - path: "**/*.py"
    instructions: |
      Please act as a Python programming mentor for the CSD325 course.
      - Ensure the code adheres to PEP 8 standards for style and readability.
      - Check for clear and concise docstrings for all modules, classes, and functions, explaining their purpose, arguments, and what they return.
      - Point out any unhandled exceptions or potential runtime errors.
      - Suggest more "Pythonic" ways to write code where applicable (e.g., using comprehensions, context managers).

  - path: "**/test_*.py"
    instructions: |
      This is a `pytest` test file. Please review it carefully.
      - Ensure that test function names are descriptive (e.g., `test_city_country_population`).
      - Confirm that appropriate pytest assertions are used (e.g., `assert x == y`, `assert value is True`).
      - Check that the tests cover both expected outcomes and edge cases.
      - Ensure the file correctly imports the functions/classes being tested.

  - path: "**/views.py"
    instructions: |
      This is a Django views file.
      - Ensure it imports `HttpResponse` from `django.http`.
      - Check that each view function accepts a `request` object as its first parameter.
      - Verify that each view returns an `HttpResponse` object.

  - path: "**/*high_low*.py"
    instructions: |
      This is a data visualization script using Matplotlib and the CSV module.
      - Check that any opened CSV files are properly closed, preferably using a `with` statement.
      - Ensure that all plots generated with Matplotlib have a title, an x-axis label, and a y-axis label for clarity.
      - Verify that different data series (e.g., highs vs. lows) are plotted in different colors to be easily distinguishable.
    