version = 1

test_patterns = [
  "**/test_*.py",
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js"
]

exclude_patterns = [
  "venv",
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"