version = 1

exclude_patterns = [
    "venv",
    "node_modules",
    "bower_components",
    "out",
    "bin",
    "build",
    "dist",
]

test_patterns = [
    "**/test_*.py",
    "**/__tests__/**",
    "**/*.spec.ts",
    "**/*.spec.js",
    "**/*.test.ts",
    "**/*.test.js",
]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"

# skipcq: FLK-E501
# Add the above
